-- Se ejecuta en PostgreSQL local efímero, nunca inserta fixtures en producción.
insert into auth.users(id) values('00000000-0000-4000-8000-000000000001'),('00000000-0000-4000-8000-000000000002'),('00000000-0000-4000-8000-000000000003');
select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000001',false);
select public.bootstrap('Ferretería pruebas A','10000000-0000-4000-8000-000000000001');
select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000002',false);
select public.bootstrap('Ferretería pruebas B','10000000-0000-4000-8000-000000000002');
select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000001',false);

create function public.test_assert(ok boolean,msg text) returns void language plpgsql as $$begin if not coalesce(ok,false) then raise exception 'TEST: %',msg; end if; end$$;
do $$
declare b uuid='10000000-0000-4000-8000-000000000001'; br uuid; w uuid; cash uuid; bank uuid; prod uuid; pres uuid; box uuid; party uuid; vendor uuid; purchase uuid; sale uuid; li uuid; sess uuid; res jsonb; stock_qty numeric; request uuid=gen_random_uuid(); payload jsonb; margin numeric;
begin
select id into br from public.branches where business_id=b;
select id into w from public.warehouses where business_id=b;
select id into cash from public.accounts where business_id=b and kind='cash';
select id into bank from public.accounts where business_id=b and kind='bank';
res=public.command(b,gen_random_uuid(),'product.save','{"code":"TOR","name":"Tornillo","price":2,"unit":"unidad","fractional":false}'); prod=(res->>'id')::uuid;
select id into pres from public.presentations where product_id=prod;
perform public.command(b,gen_random_uuid(),'presentation.save',jsonb_build_object('product_id',prod,'name','Caja 100','factor',100,'price',200));
select id into box from public.presentations where product_id=prod and factor=100;
res=public.command(b,gen_random_uuid(),'party.save','{"name":"Proveedor","kind":"supplier"}'); vendor=(res->>'id')::uuid;
res=public.command(b,gen_random_uuid(),'party.save','{"name":"Cliente crédito","kind":"customer","credit_limit":10000}'); party=(res->>'id')::uuid;
res=public.command(b,gen_random_uuid(),'cash.open',jsonb_build_object('account_id',cash,'opening',100)); sess=(res->>'id')::uuid;
res=public.command(b,gen_random_uuid(),'document.create',jsonb_build_object('kind','purchase','branch_id',br,'warehouse_id',w,'party_id',vendor,'lines',jsonb_build_array(jsonb_build_object('product_id',prod,'presentation_id',box,'quantity',1,'price',100)))); purchase=(res->>'id')::uuid;
perform public.test_assert(not exists(select 1 from public.stock where product_id=prod),'Orden no aumenta inventario');
perform public.command(b,gen_random_uuid(),'purchase.confirm',jsonb_build_object('id',purchase));
res=public.command(b,gen_random_uuid(),'payment.create',jsonb_build_object('branch_id',br,'party_id',vendor,'direction','out','payments',jsonb_build_array(jsonb_build_object('account_id',bank,'amount',50)),'applications',jsonb_build_array(jsonb_build_object('document_id',purchase,'amount',50))));
perform set_config('test.supplier_payment_id',res->>'id',false);
perform public.test_assert((select balance=50 from public.document_balances where id=purchase),'Abono de proveedor reduce deuda sin gasto duplicado');
select id into li from public.document_lines where document_id=purchase;
perform public.command(b,gen_random_uuid(),'purchase.receive',jsonb_build_object('id',purchase,'lines',jsonb_build_array(jsonb_build_object('line_id',li,'quantity',40))));
perform public.test_assert((select physical=40 from public.stock where product_id=prod),'Recepción parcial');
perform public.command(b,gen_random_uuid(),'purchase.receive',jsonb_build_object('id',purchase,'lines',jsonb_build_array(jsonb_build_object('line_id',li,'quantity',60))));
payload=jsonb_build_object('kind','sale','branch_id',br,'warehouse_id',w,'lines',jsonb_build_array(jsonb_build_object('product_id',prod,'presentation_id',pres,'quantity',15)), 'payments',jsonb_build_array(jsonb_build_object('account_id',cash,'amount',10),jsonb_build_object('account_id',bank,'amount',20)));
res=public.command(b,request,'document.create',payload); sale=(res->>'id')::uuid;
perform public.test_assert((select physical=85 from public.stock where product_id=prod),'Caja 100 menos venta 15 = 85');
perform public.test_assert((select count(*)=2 from public.money_moves where kind='collection'),'Pagos combinados');
perform public.test_assert(public.command(b,request,'document.create',payload)=res,'Reintento idempotente');
perform public.test_assert((select physical=85 from public.stock where product_id=prod),'Reintento no descuenta otra vez');
select id into li from public.document_lines where document_id=sale;
perform public.command(b,gen_random_uuid(),'return.create',jsonb_build_object('document_id',sale,'line_id',li,'quantity',5,'reason','Cambio solicitado','account_id',cash));
perform public.test_assert((select physical=90 from public.stock where product_id=prod),'Devolución parcial repone');
perform public.test_assert((select balance=0 from public.document_balances where id=sale),'Reembolso sin deuda negativa');
begin perform public.command(b,gen_random_uuid(),'return.create',jsonb_build_object('document_id',sale,'line_id',li,'quantity',11,'reason','Exceso')); raise exception 'TEST: devolución excesiva aceptada'; exception when others then if SQLERRM like 'TEST:%' then raise; end if; end;
res=public.command(b,gen_random_uuid(),'document.create',jsonb_build_object('kind','sale','branch_id',br,'warehouse_id',w,'party_id',party,'credit',true,'due_date',current_date+30,'deferred',true,'lines',jsonb_build_array(jsonb_build_object('product_id',prod,'presentation_id',pres,'quantity',5)), 'payments','[]'::jsonb)); sale=(res->>'id')::uuid;
perform public.command(b,gen_random_uuid(),'payment.create',jsonb_build_object('branch_id',br,'party_id',party,'direction','in','payments',jsonb_build_array(jsonb_build_object('account_id',cash,'amount',4)),'applications',jsonb_build_array(jsonb_build_object('document_id',sale,'amount',4))));
perform public.test_assert((select balance=6 from public.document_balances where id=sale),'Abono reduce deuda');
perform public.test_assert((select count(*)=2 from public.documents where kind='sale'),'Abono no crea venta');
select id into li from public.document_lines where document_id=sale;
select physical into stock_qty from public.stock where product_id=prod;
perform public.command(b,gen_random_uuid(),'delivery.create',jsonb_build_object('document_id',sale,'line_id',li,'quantity',3,'contact','Cliente'));
perform public.test_assert((select physical=stock_qty from public.stock where product_id=prod),'Entrega no descuenta dos veces');
margin=(public.report(b,current_date,current_date)->>'gross_margin')::numeric;
perform public.command(b,gen_random_uuid(),'inventory.adjust',jsonb_build_object('warehouse_id',w,'product_id',prod,'quantity',100,'cost',20,'reason','Entrada adicional'));
perform public.test_assert((public.report(b,current_date,current_date)->>'gross_margin')::numeric=margin,'Margen histórico conserva costo snapshot');
res=public.command(b,gen_random_uuid(),'product.save','{"code":"CAB","name":"Cable","price":10,"fractional":true}'); prod=(res->>'id')::uuid;
select id into pres from public.presentations where product_id=prod;
perform public.command(b,gen_random_uuid(),'inventory.adjust',jsonb_build_object('warehouse_id',w,'product_id',prod,'quantity',5,'cost',2,'reason','Entrada inicial'));
perform public.command(b,gen_random_uuid(),'document.create',jsonb_build_object('kind','sale','branch_id',br,'warehouse_id',w,'lines',jsonb_build_array(jsonb_build_object('product_id',prod,'presentation_id',pres,'quantity',1.25)), 'payments',jsonb_build_array(jsonb_build_object('account_id',cash,'amount',12.5))));
perform public.test_assert((select physical=3.75 from public.stock where product_id=prod),'Venta decimal');
begin perform public.command(b,gen_random_uuid(),'document.create',jsonb_build_object('kind','sale','branch_id',br,'warehouse_id',w,'lines',jsonb_build_array(jsonb_build_object('product_id',prod,'presentation_id',pres,'quantity',4)), 'payments',jsonb_build_array(jsonb_build_object('account_id',cash,'amount',40)))); raise exception 'TEST: venta sin stock aceptada'; exception when others then if SQLERRM like 'TEST:%' then raise; end if; end;
perform public.test_assert((select physical=3.75 from public.stock where product_id=prod),'Venta fallida revierte toda la transacción');
perform public.command(b,gen_random_uuid(),'expense_rule.save',jsonb_build_object('branch_id',br,'description','Renta','category','Local','amount',100,'frequency','monthly','next_date',current_date));
perform private.generate_expenses(); perform private.generate_expenses();
perform public.test_assert((select count(*)=1 from public.expenses),'Gastos recurrentes sin duplicados');
perform public.test_assert((select paid_at is null from public.expenses limit 1),'Programar no paga gasto');
perform public.command(b,gen_random_uuid(),'cash.close',jsonb_build_object('id',sess,'counted',110,'reason','Diferencia documentada'));
perform public.test_assert((select expected=116.5 and counted=110 from public.sessions where id=sess),'Caja con diferencia');
margin=(public.report(b,current_date,current_date)->>'gross_margin')::numeric;
res=public.command(b,gen_random_uuid(),'product.save','{"code":"IMP","name":"Producto con impuesto","price":10,"tax_rate":15,"fractional":false}'); prod=(res->>'id')::uuid;
select id into pres from public.presentations where product_id=prod;
perform public.command(b,gen_random_uuid(),'inventory.adjust',jsonb_build_object('warehouse_id',w,'product_id',prod,'quantity',5,'cost',2,'reason','Entrada inicial'));
res=public.command(b,gen_random_uuid(),'document.create',jsonb_build_object('kind','sale','branch_id',br,'warehouse_id',w,'lines',jsonb_build_array(jsonb_build_object('product_id',prod,'presentation_id',pres,'quantity',2)), 'payments',jsonb_build_array(jsonb_build_object('account_id',bank,'amount',23))));sale=(res->>'id')::uuid;
perform public.test_assert((public.report(b,current_date,current_date)->>'gross_margin')::numeric=margin+16,'Margen excluye impuesto');
select id into li from public.document_lines where document_id=sale;
perform public.command(b,gen_random_uuid(),'return.create',jsonb_build_object('document_id',sale,'line_id',li,'quantity',1,'damaged',true,'reason','Producto averiado','account_id',bank));
perform public.test_assert((public.report(b,current_date,current_date)->>'gross_margin')::numeric=margin+6,'Devolución dañada conserva costo perdido');
perform public.test_assert((select physical=3 and damaged=1 from public.stock where product_id=prod),'Dañados separados de vendibles');
perform public.test_assert((public.read_data(b,'products','imp')->>'count')::integer=1,'Búsqueda por código indexada');
perform public.test_assert((public.report(b,current_date,current_date,null,'00000000-0000-4000-8000-000000000002')->>'sales')::numeric=0,'Reporte filtrado por autor');
perform public.test_assert((public.read_data(b,'units')->>'count')::integer>0,'Unidades normalizadas por negocio');
perform public.test_assert(jsonb_array_length(public.read_data(b,'payments')->'rows'->0->'applications')>0,'Recibos contienen aplicaciones verificables');
perform public.test_assert((public.read_data(b,'stock')->'rows'->0->>'average') is not null,'Valorización autorizada en inventario');
res=public.command(b,gen_random_uuid(),'document.create',jsonb_build_object('kind','quote','branch_id',br,'warehouse_id',w,'valid_until',current_date+5,'lines',jsonb_build_array(jsonb_build_object('product_id',prod,'presentation_id',pres,'quantity',1))));purchase=(res->>'id')::uuid;
perform public.test_assert((select physical=3 and reserved=0 from public.stock where product_id=prod),'Cotización no reserva automáticamente');
select id into li from public.document_lines where document_id=purchase;
perform public.command(b,gen_random_uuid(),'quote.reserve',jsonb_build_object('document_id',purchase,'line_id',li,'quantity',1,'expires_at',current_date+1));
perform public.test_assert((select physical=3 and reserved=1 from public.stock where product_id=prod),'Reserva explícita reduce solo disponible');
res=public.command(b,gen_random_uuid(),'document.create',jsonb_build_object('kind','sale','branch_id',br,'warehouse_id',w,'origin_id',purchase,'lines',jsonb_build_array(jsonb_build_object('product_id',prod,'presentation_id',pres,'quantity',1)),'payments',jsonb_build_array(jsonb_build_object('account_id',bank,'amount',11.5))));sale=(res->>'id')::uuid;
perform public.test_assert((select physical=2 and reserved=0 from public.stock where product_id=prod),'Convertir libera reserva y descuenta una vez');
begin perform public.command(b,gen_random_uuid(),'document.create',jsonb_build_object('kind','sale','branch_id',br,'warehouse_id',w,'origin_id',purchase,'lines',jsonb_build_array(jsonb_build_object('product_id',prod,'presentation_id',pres,'quantity',1)),'payments',jsonb_build_array(jsonb_build_object('account_id',bank,'amount',11.5))));raise exception 'TEST: conversión duplicada';exception when others then if SQLERRM like 'TEST:%' then raise;end if;end;
perform public.command(b,gen_random_uuid(),'document.void',jsonb_build_object('id',sale,'reason','Anulación de prueba','account_id',bank));
perform public.test_assert((select physical=3 from public.stock where product_id=prod),'Anulación revierte inventario');
perform public.test_assert((public.report(b,current_date,current_date)->>'gross_margin')::numeric=margin+6,'Anulación revierte margen en su fecha');
perform public.test_assert((select voided_at is not null from public.documents where id=sale),'Anulación conserva fecha y motivo');
res=public.command(b,gen_random_uuid(),'document.create',jsonb_build_object('kind','quote','branch_id',br,'warehouse_id',w,'valid_until',current_date+1,'lines',jsonb_build_array(jsonb_build_object('product_id',prod,'presentation_id',pres,'quantity',1))));purchase=(res->>'id')::uuid;
select id into li from public.document_lines where document_id=purchase;
perform public.command(b,gen_random_uuid(),'quote.reserve',jsonb_build_object('document_id',purchase,'line_id',li,'quantity',1,'expires_at',current_date+1));
perform public.command(b,gen_random_uuid(),'quote.state',jsonb_build_object('id',purchase,'state','rejected'));
perform public.test_assert((select reserved=0 from public.stock where product_id=prod),'Rechazar cotización libera reserva');
perform public.command(b,gen_random_uuid(),'money.adjust',jsonb_build_object('account_id',bank,'direction','deposit','amount',50,'reference','Aporte del dueño'));
perform public.command(b,gen_random_uuid(),'money.transfer',jsonb_build_object('from_account',bank,'to_account',(select id from public.accounts where business_id=b and kind='card'),'amount',5,'reference','Transferencia de prueba'));
perform public.test_assert((public.report(b,current_date,current_date)->>'gross_margin')::numeric=margin+6,'Aportes y transferencias no crean utilidad');
perform public.command(b,gen_random_uuid(),'expense_rule.toggle',jsonb_build_object('id',(select id from public.expense_rules where business_id=b limit 1),'active',false));
perform public.test_assert((select not active from public.expense_rules where business_id=b limit 1),'Programación se puede pausar sin borrar obligaciones');
perform public.command(b,gen_random_uuid(),'numbering.save',jsonb_build_object('kind','quote','prefix','COT-','next_number',100));
res=public.command(b,gen_random_uuid(),'document.create',jsonb_build_object('kind','quote','branch_id',br,'warehouse_id',w,'lines',jsonb_build_array(jsonb_build_object('product_id',prod,'presentation_id',pres,'quantity',1))));
perform public.test_assert(res->>'number'='100' and res->>'number_prefix'='COT-','Numeración independiente por negocio y tipo');
begin perform public.command(b,gen_random_uuid(),'cash.close',jsonb_build_object('id',sess,'counted',1,'reason','Reabrir')); raise exception 'TEST: cierre repetido'; exception when others then if SQLERRM like 'TEST:%' then raise; end if; end;
perform public.test_assert(not private.allowed('10000000-0000-4000-8000-000000000002','read'),'Aislamiento de autorización');
insert into public.memberships(business_id,user_id,role) values(b,'00000000-0000-4000-8000-000000000003','VENDEDOR');
end $$;
set role authenticated;
select public.test_assert((select count(*)=1 from public.businesses),'RLS oculta negocio B');
select public.test_assert((select count(*)=0 from public.products where business_id='10000000-0000-4000-8000-000000000002'),'RLS acceso directo cruzado');
select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000003',false);
select public.test_assert(not private.allowed('10000000-0000-4000-8000-000000000001','inventory.write'),'Vendedor no ajusta');
select public.test_assert((select count(*)=0 from public.line_costs),'Costos protegidos');
select public.test_assert((public.read_data('10000000-0000-4000-8000-000000000001','payments','',0,jsonb_build_object('id',current_setting('test.supplier_payment_id')))->>'count')::integer=0,'Pago de proveedor no accesible por ID a vendedor');
select public.test_assert(not ((public.read_data('10000000-0000-4000-8000-000000000001','stock')->'rows'->0) ? 'average'),'RPC oculta costo de stock a vendedor');
select public.test_assert(not exists(select 1 from jsonb_array_elements(public.read_data('10000000-0000-4000-8000-000000000001','payments')->'rows') r where exists(select 1 from public.payment_applications a join public.documents d on d.id=a.document_id where a.payment_id=(r->>'id')::uuid and d.kind='purchase')),'RPC oculta pagos de compras sin costo autorizado');
do $$begin
begin perform public.command('10000000-0000-4000-8000-000000000001',gen_random_uuid(),'inventory.adjust','{}'); raise exception 'TEST: vendedor ajustó'; exception when others then if SQLERRM like 'TEST:%' then raise; end if; end;
begin update public.memberships set role='ADMIN'; raise exception 'TEST: escalada de privilegios'; exception when insufficient_privilege then null; end;
end $$;
reset role;
